### ISSUE TITLE
x264 module is not reproducable

### ISSUE THREAD

**Issue by TingPing** [flathub/com.ozmartians.VidCutter#1]
It is building from HEAD.

**Comment by ozmartian** [comment]
@TingPing will fix that right now but must ask what the process is now that this has been published? do i fork this new repo or continue to make changes to the forked repo from the initial pull request?

cheers

**Comment by nedrichards** [comment]
@ozmartian Pull Requests on this new repo. You can also run your own test builds by saying "bot, build" in a PR - the output is at https://flathub.org/builds

**Comment by ozmartian** [comment]
@nedrichards nice one, thx for the tips.. just created PR and will give the test build a run..

**Comment by TingPing** [comment]
And once everything builds (which it did) and you are satisfied you can merge it.

**Comment by ozmartian** [comment]
@TingPing not sure if i'm missing something but I don't seem to have write access to the repo... am listed as a contributor but everything is read only...

**Comment by nedrichards** [comment]
You can't press the merge button on the PR? I'll take a look when I'm back
at a computer unless someone else gets there first. Sorry if there's a
problem!

**Comment by ozmartian** [comment]
@nedrichards no merge button is present as per read-only access... no rush, no apologies necessary either :) thx!

**Comment by TingPing** [comment]
The invite was sent but you have to accept it. I believe you get an email and it shows up somewhere on this site though not sure where offhand.

**Comment by ozmartian** [comment]
ahh i haven't checked my email in a few days... lol, knew it was me and not you guys :) i'll go sort that out now... thx
