### ISSUE TITLE
com.ozmartians.VidCutter uses end-of-life runtimes

### ISSUE THREAD

**Issue by rmbleeker** [flathub/com.ozmartians.VidCutter#29]
VidCutter is using the following runtimes that are end-of-life:

- org.kde.Platform branch 5.15-21.08
- org.freedesktop.Platform.GL.default branch 21.08

I hope the flatpak can be updated to use newer versions of those runtimes.

**Comment by ozmartian** [comment]
In process of updating to KDE runtime 5.15-22.08
